services:
  - type: web
    name: supetz-confiante
    branch: main
    autoDeployTrigger: commit
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
